### ISSUE TITLE
Some zip files can't be extracted

### ISSUE THREAD

**Issue by JCWasmx86** [tsolomko/SWCompression#42] opened 2023-04-02 10:45 UTC
I tested it with the develop branch and the tag 4.8.5

```
> wget https://github.com/richgel999/miniz/releases/download/3.0.1/miniz-3.0.1.zip
> ./swcomp zip -e foo miniz-3.0.1.zip -v
d = directory, f = file, l = symbolic link
f: miniz.c
f: miniz.h
f: examples/example1.c
Error: The operation could not be completed. The file doesn’t exist.
> ls foo
miniz.c  miniz.h (There should be a directory examples)
> wget https://www.sqlite.org/2023/sqlite-amalgamation-3410200.zip
> ./swcomp zip -e foo sqlite-amalgamation-3410200.zip
... Successful ....
```

**Comment by tsolomko** [comment] 2023-04-05 10:58
Hi,

The cause of this issue is that the ZIP archive in your first example does not contain an entry for the "examples" directory, so it is not created when extracting an archive, and thus creating a file inside a non-existent directory fails.

This is not an issue with SWCompression itself, as it is not its goal to evaluate the contents of the archives it is processing apart from the general format correctness (and there is no provision in ZIP format specifications that requires the existence of directory entries).

It can be argued that swcomp should check for this situation and I am still deliberating if/how/when this issue should be fixed, but as a general reminder, swcomp is not intended for general use.

**Comment by JCWasmx86** [comment] 2023-04-05 11:13
Ah ok. I apologize for the disturbance. I will close the issue

**Closed** 2023-04-05 11:13 UTC
